#!/bin/sh

if [ "$#" -lt 4 ]
then
	echo "Usage: $0 <docker_app_name> <bids_test_data_url> <out folder> <analysis_level> <opt args...>"
#	exit 1
fi

DOCKER_NAME=$1
TESTDATA_URL=$2
OUT_FOLDER=$3
ANALYSIS_LEVEL=$4

shift 4

OPTARGS=$@

#TESTDATA_URL=https://www.dropbox.com/s/dp238bmdkowj35q/t1w.tar
#DOCKER_NAME=khanlab/beast:latest
#ANALYSIS_LEVEL=participant

mkdir -p bids 
wget -qO- $TESTDATA_URL | tar xv -C bids
docker create -v /data --name testdata alpine:3.4 /bin/true
docker cp bids testdata:/data
docker run  --name testapp  --volumes-from testdata -it $DOCKER_NAME /data/bids /out $ANALYSIS_LEVEL  $OPTARGS
docker cp testapp:/out $OUT_FOLDER

